export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_COLLAPSE = 'SIDEBAR_COLLAPSE'




// REGISTER
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_ERROR_CLEAR = 'REGISTER_ERROR_CLEAR'
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE'



// LOGIN
export const SET_LOGIN_USER = 'SET_LOGIN_USER'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_ERROR_CLEAR = 'LOGIN_ERROR_CLEAR'

// information
export const BUY_CHICKEN = 'BUY_CHICKEN'
export const DEATH_CHICKENS = 'DEATH_CHICKENS'
export const BUY_FEED = 'BUY_FEED'
export const FINISH_FEED = 'FINISH_FEED'
export const BUY_MEDICINE = 'BUY_MEDICINE'
export const OTHERS_COST = 'OTHERS_COST'


// LOGOUT
export const LOGOUT_USER = 'LOGOUT_USER'

// ADMIN
export const SET_ADMIN = 'SET_ADMIN'

// ALL-USER INFORMATION
export const ALL_USER_DATA = 'ALL_USER_DATA'


// feed
export const FEED_UPDATE_ID = 'FEED_UPDATE_ID'
export const FEED_UPDATE_ID_2 = 'FEED_UPDATE_ID_2'
export const FEED_UPDATE_NAME = 'FEED_UPDATE_NAME'
export const FEED_UPDATE_CATEGORY = 'FEED_UPDATE_CATEGORY'
export const FEED_UPDATE_BAG = 'FEED_UPDATE_BAG'
export const FEED_UPDATE_PRICE = 'FEED_UPDATE_PRICE'
export const FEED_UPDATE_DATE = 'FEED_UPDATE_DATE'

// finish feed
export const FEED_FINISH_UPDATE_ID = 'FEED_FINISH_UPDATE_ID'
export const FEED_FINISH_UPDATE_ID_2 = 'FEED_FINISH_UPDATE_ID_2'
export const FEED_FINISH_UPDATE_NAME = 'FEED_FINISH_UPDATE_NAME'
export const FEED_FINISH_UPDATE_CATEGORY = 'FEED_FINISH_UPDATE_CATEGORY'
export const FEED_FINISH_UPDATE_BAG = 'FEED_FINISH_UPDATE_BAG'
export const FEED_FINISH_UPDATE_DATE = 'FEED_FINISH_UPDATE_DATE'

// medicine
export const MEDICINE_UPDATE_ID = 'MEDICINE_UPDATE_ID'
export const MEDICINE_UPDATE_ID_2 = 'MEDICINE_UPDATE_ID_2'
export const MEDICINE_UPDATE_NAME = 'MEDICINE_UPDATE_NAME'
export const MEDICINE_UPDATE_QUANTITY = 'MEDICINE_UPDATE_QUANTITY'
export const MEDICINE_UPDATE_COMPANY = 'MEDICINE_UPDATE_COMPANY'
export const MEDICINE_UPDATE_GROUP = 'MEDICINE_UPDATE_GROUP'
export const MEDICINE_UPDATE_PRICE = 'MEDICINE_UPDATE_PRICE'
export const MEDICINE_UPDATE_DATE = 'MEDICINE_UPDATE_DATE'



// chicken buy
export const CHICKS_UPDATE_ID = 'CHICKS_UPDATE_ID'
export const CHICKS_UPDATE_ID_2 = 'CHICKS_UPDATE_ID_2'
export const CHICKS_UPDATE_COMPANY = 'CHICKS_UPDATE_COMPANY'
export const CHICKS_UPDATE_QUANTITY = 'CHICKS_UPDATE_QUANTITY'
export const CHICKS_UPDATE_PRICE = 'CHICKS_UPDATE_PRICE'
export const CHICKS_UPDATE_DATE = 'CHICKS_UPDATE_DATE'
export const CHICKS_UPDATE_SALESTIME = 'CHICKS_UPDATE_TIME'
export const CHICKS_SELL_STATUS = 'CHICKS_SELL_STATUS'


// chicken death
export const CHICKS_DEATH_UPDATE_ID = 'CHICKS_DEATH_UPDATE_ID'
export const CHICKS_DEATH_UPDATE_ID_2 = 'CHICKS_DEATH_UPDATE_ID_2'
export const CHICKS_DEATH_UPDATE_REASON = 'CHICKS_DEATH_UPDATE_REASON'
export const CHICKS_DEATH_UPDATE_DATE = 'CHICKS_DEATH_UPDATE_DATE'
export const CHICKS_DEATH_UPDATE_TIME = 'CHICKS_DEATH_UPDATE_TIME'
export const CHICKS_DEATH_UPDATE_DEATH = 'CHICKS_DEATH_UPDATE_DEATH'
